# .pre-commit-config.yaml
repos:
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.9.1
    hooks:
      - id: nbqa-black
        files: \.ipynb$
        args: [--line-length=100]
        additional_dependencies:
          - black==24.8.0
      - id: nbqa-ruff
        files: \.ipynb$
        args: [--extend-ignore=E402 , --fix]
        additional_dependencies:
          - ruff==0.6.9
      - id: nbqa-mypy
        files: \.ipynb$
        additional_dependencies:
          - mypy

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: [--extend-ignore=E402, --fix]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.2
    hooks:
      - id: mypy
        args: [--strict, --ignore-missing-imports]